export {
  BarChart3 as AnalyticsIcon,
  Bell as BellIcon,
  Briefcase as BudgetIcon,
  BarChart as ChartIcon,
  Beef as CowIcon,
  FileText as FileIcon,
  FileBarChart as ReportIcon,
  DollarSign as RevenueIcon,
  MinusCircle as ExpenseIcon,
  Settings as SettingsIcon,
  ClipboardList as TaskIcon,
  Truck as TruckIcon,
  Users as UsersIcon,
  UserCircle,
  Calendar as CalendarIcon,
  CheckCircle as CompletedIcon,
  Clock as PendingIcon,
  Activity as ActivityIcon,
  Heart as HealthIcon,
  Stethoscope as MedicalIcon,
  AlertCircle as AlertIcon,
  LineChart as PerformanceIcon,
  Target as GoalIcon,
  ListChecks as ChecklistIcon,
  // Add any missing icons here
} from 'lucide-react'; 